# Generated by Django 6.0.6 on 2026-06-28 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JalibotConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_session_id', models.UUIDField(blank=True, null=True)),
                ('messages', models.JSONField(default=list)),
                ('crisis_detected', models.BooleanField(default=False)),
                ('crisis_keywords_found', models.JSONField(default=list)),
                ('referred_to_counselor', models.BooleanField(default=False)),
                ('referred_counselor_id', models.UUIDField(blank=True, null=True)),
                ('session_started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('message_count_this_hour', models.PositiveSmallIntegerField(default=0)),
                ('hour_window_start', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jalibot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jalibot_conversation',
                'indexes': [models.Index(fields=['user', 'session_started_at'], name='jalibot_con_user_id_21b173_idx'), models.Index(fields=['anonymous_session_id'], name='jalibot_con_anonymo_7fa415_idx')],
            },
        ),
    ]
