# Generated by Django 6.0.6 on 2026-07-07 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalibot', '0002_jalibotconversation_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JalibotMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('emotional', 'Emotional'), ('family', 'Family'), ('career', 'Career'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='jalibot.jalibotconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jalibot_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jalibot_memory',
                'ordering': ['-created_at'],
            },
        ),
    ]
