# Generated by Django 6.0.6 on 2026-06-28 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('accepts_anonymous', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='counselors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'counselors_profile',
            },
        ),
        migrations.CreateModel(
            name='CounselorAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='counselors.counselorprofile')),
            ],
            options={
                'db_table': 'counselors_availability_slot',
                'unique_together': {('counselor', 'day_of_week', 'start_time')},
            },
        ),
    ]
