# Generated by Django 6.0.6 on 2026-06-28 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pseudonym', models.CharField(max_length=40, unique=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('referred_counselor_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crisis_flagged', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shadow_anonymous_session',
                'indexes': [models.Index(fields=['expires_at', 'is_active'], name='shadow_anon_expires_644ce9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnonymousMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('counselor', 'Counselor')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shadow_chat.anonymoussession')),
            ],
            options={
                'db_table': 'shadow_anonymous_message',
                'ordering': ['created_at'],
            },
        ),
    ]
