# Generated by Django 6.0.6 on 2026-06-28 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counselors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=15)),
                ('session_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text Chat'), ('anonymous', 'Anonymous Text'), ('voice', 'Voice')], default='text', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('counselor_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=300)),
                ('meeting_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_appointments', to='counselors.counselorprofile')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions_appointment',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='booking_sessions.appointment')),
            ],
            options={
                'db_table': 'sessions_review',
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['student', 'status'], name='sessions_ap_student_6167c3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['counselor', 'scheduled_at'], name='sessions_ap_counsel_42c1d9_idx'),
        ),
    ]
